version: "3.7"
 
services:
  database:
    container_name: prexicoin_mysql
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: "${DB_NAME_APP}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3307:3306"
    volumes: 
      - vol_prexicoin_mysql:/var/lib/mysql
    networks:
      - back  
  app:
    container_name: prexicoin_app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "3334:3334"
    volumes:
      - ./backend/src:/prexicoin-app/:cached
    depends_on:
      - database
    networks:
      - back

networks:
  back:
    driver: bridge

volumes:
  vol_prexicoin_mysql:
