# base image
FROM node:14.19.1

RUN yarn cache clean --force

COPY frontend/panels/www /prexicoin-app/panels/www/
WORKDIR /prexicoin-app/panels/www/
RUN yarn install

EXPOSE 3336

CMD [ "yarn", "dev"]